@startuml

class AbstractCheck {
    + public_stuff
    # _is_venv_required
    # _project_root
    - __goal
    # _name
    # _pre_run(self) : void
    + foo(pos_or_keyword: str, kwargs, kw_only_1, kw_only_2, self, pos_only_1: int, pos_only_2: int, args) : void
}


class ScoredCheck {
    # _max_points
}


@enduml
